[package]
name = "bot"
version = "0.1.0"
authors = ["vancha"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy_rss = "1.0.1"
serde_json = "1.0.64"
elefren = "0.22"
toml = "0.5.8"
